### PR TITLE
Issue/123/remove-login

### LINKED ISSUE #123: Removal of Login files and config.
Describe the bug
We need to delete the Login page because it's no longer relevant.

Additional context
We are working on sterilizing the framework.

We need to remove

the route from serverless.yaml.
the lambda file.
the template page.

### PR DESCRIPTION
**Pull request by hunterAlbertJ**
## What is the story, issue or feature this Pull Request is solving or implementing?

We no longer require login files and config

## What is the approach you are using to solve the issue above?
deleted login.js
deleted related relative lambda from serverless.yaml

## What are the changes that this Pull Request is introducing?
See above

## Is there something this Pull Request is dependent on before it can be merged in?

No
## Completeness Checklist
- [ ] Local Tests are passing.
- [ ] New tests have been added for new code.
- [ ] JSDoc Documentation and comments have been added or updated in the code.
- [ ] Documentation in the /docs folder has been added or updated when appropirate.
- [ ] Follows Nouri JavaScript guidelines
- [ ] Commit message follows Nouri guidelines
- [ ] Introduces minimal or no additional external packages.

## What Issue number is this related to?

Closes #123

### CODE REVIEW

**Review by devPalacio — CHANGES_REQUESTED** [review]
/templates/login.html requires removal as well

**Review by devPalacio — APPROVED** [review]

**Review by devPalacio — CHANGES_REQUESTED** [review]
Something strange happened when you tried to squash your commits and the tree is probably all jacked up, this pull request is asking to pull in 6 different commits, it should only be 1 or 2 commits max. I'm not sure what the best way to unwind this is.

**Comment by devPalacio** [comment]
image

**Comment by ambergkim** [comment]
@devPalacio @hunterAlbertJ Looks like a merge into the feature branch was done instead of a rebase on top of master. Clue is in the title of [the commits](https://github.com/trellistk/trellis-sls-ssr-starter/pull/126/commits).

To make things simpler, I would create a new branch off of master, then cherry pick the commit from the old branch. Or, if it's easier, start over since the changes are not big.

**Comment by devPalacio** [comment]
I took pictures of the trees, but wasn't able to put it into words, thanks amber!

**Comment by hunterAlbertJ** [comment]
Looks like I’ve achieved a level where my ineptitude can cause tangible headaches, my apologies I will fix this in the morning.

**Comment by devPalacio** [comment]
This a positive, friendly learning environment. You're doing good Hunter! Git is not easy.

**Comment by ambergkim** [comment]
👆this

**Pull request closed without merging**
